#!/bin/sh

echo "dotfiles 0.2 by mntcloud"
echo "This script will setup up your *nix system"
echo ""

echo "Checking operating system..."
os="$(uname)"

if [ "$os" = "Darwin" ]; then
    echo "Hello macOS!"
    echo "Checking package manager installation..."

    # Getting brew path
    manager="$(which brew)"

    if [[ -n $manager ]]; then
        echo "Homebrew is installed"
    else 
        echo "Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    echo "Installing formulas..."

    pkgs=(
        'fish' 
        'clojure' 
        'ninja' 
        'cmake' 
        'tmux' 
        'neovim' 
        'qemu' 
        'htop'
	'git' # overlap git from the command line tools
        'python@3.9' 
        'crystal' 
        'ruby' 
        'go'
        'node'
        'yarn'
        'meson'
        'php'
        'deno'
        'rustup-init'
    )

    for pkg in "${pkgs[@]}"; do
	echo "Installing $pkg..."
        brew install $pkg
    done   

    echo "Installing Rust toolkit..."
    rustup-init
    fish -c "fish_add_path ~/.cargo/bin"
    echo "OK"
    
    echo "Installing Heroku and Firebase tools..."
    fish -c "npm install -g heroku"
    echo "OK"
    fish -c "npm install -g firebase-tools"
    echo "OK"

    echo "Setting up Ruby..."
    fish -c "fish_add_path /usr/local/opt/ruby/bin"
    fish -c "gem update --system"
    echo "OK"

    echo "Installing configs..."
    
    echo "Fish Shell:"
    mkdir -p ~/.config/fish
    cp -r fish ~/.config/fish
    echo "OK"

    echo "Done!"
elif [ "$os" = "Linux" ]; then
    echo "Hello Tux!"
    echo "TODO: Write Linux version of the script"
else
    echo "This script doesn't support your system!"
fi
