#!/bin/sh

echo "dotfiles 2.0 by heimdalllr"
echo "This script will setup up your *nix system"
echo ""

echo "Checking operating system..."
os="$(uname)"

if [ "$os" = "Darwin" ]; then
    echo "Hello macOS!"
    echo "Checking package manager installation..."

    # Getting brew path
    manager="$(which brew)"

    if [ manager != "" ]; then
        echo "Homebrew is installed"
    else 
        echo "Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    echo "Installing formulas..."

    pkgs=(
        'fish' 
        'clojure' 
        'ninja' 
        'cmake' 
        'tmux' 
        'neovim' 
        'qemu' 
        'htop' 
        'python@3.9' 
        'crystal' 
        'ruby' 
        'go'
        'node'
        'yarn'
        'meson'
        'rustup-init'
    )

    for pkg in "${pkgs[@]}"; do
        brew install $pkg
    done   

    echo "Changing default shell to fish..."    
    if chsh -s /usr/local/bin/fish; then 
        echo "OK"
    else 
        echo "Can't change default shell to fish"
        echo "Exiting..."
        exit
    fi

    echo "Installing official alternate cask versions repo..."
    brew tap homebrew/cask-versions
    echo "OK"

    echo "Installing casks..."    
    casks=(
        'visual-studio-code'
        'firefox'
        'firefox-developer-edition'
        'google-chrome-dev'
        'intellij-idea-ce'
        'discord'
        'iterm2'
        'notion'
        'telegram'
        'spotify'
        'docker'
    )

    for cask in "${casks[@]}"; do 
        brew install --cask $cask
    done

    echo "Installing official cask font repo..."
    brew tap homebrew/cask-fonts
    echo "OK"

    echo "Installing fonts..."
    brew install font-jetbrains-mono font-roboto-mono
    echo "OK"

    echo "Installing Rust toolkit..."
    rustup-init
    fish -c fish_add_path ~/.cargo/bin
    echo "OK"
    
    echo "Installing Heroku and Firebase tools..."
    fish -c npm install -g heroku
    echo "OK"
    fish -c npm install -g firebase-tools
    echo "OK"

    echo "Setting up Ruby..."
    fish -c fish_add_path /usr/local/opt/ruby/bin
    gem update --system
    echo "OK"

    echo "Installing configs..."
    
    echo "Fish Shell:"
    mkdir -p ~/.config/fish
    cp -r fish ~/.config/fish
    echo "OK"

    echo "Done!"
elif [ "$os" = "Linux" ]; then
    echo "Hello Tux!"
    echo "TODO: Write Linux version of the script"
else
    echo "This script doesn't support your system!"
fi