#! /bin/sh

sxhkd &
xrandr --output HDMI-0 --scale 1.1x1.1 &
xrdb -merge ~/.Xresources &
picom --config ~/.config/picom.conf -f &
~/.config/polybar/launch.sh &
nitrogen --restore &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          8

# Set the border colors.
bspc config normal_border_color "#121212"
bspc config active_border_color "#81a1c1"
bspc config focused_border_color "#81a1c1"
bspc config presel_feedback_color "$color1"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
